insert into category (name) values (  '상의');
insert into category (name) values (  '아우터');
insert into category (name) values (  '바지');
insert into category (name) values (  '스니커즈');
insert into category (name) values (  '가방');
insert into category (name) values (  '모자');
insert into category (name) values (  '양말');
insert into category (name) values (  '액세서리');

INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (1, 'A', 11200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (1, 'B', 10500);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (1, 'C', 10000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (1, 'D', 10100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (1, 'E', 10700);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (1, 'F', 11200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (1, 'G', 10500);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (1, 'H', 10800);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (1, 'I', 11400);

INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (2, 'A', 5500);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (2, 'B', 5900);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (2, 'C', 6200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (2, 'D', 5100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (2, 'E', 5000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (2, 'F', 7200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (2, 'G', 5800);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (2, 'H', 6300);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (2, 'I', 6700);

INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (3, 'A', 4200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (3, 'B', 3800);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (3, 'C', 3300);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (3, 'D', 3000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (3, 'E', 3800);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (3, 'F', 4000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (3, 'G', 3900);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (3, 'H', 3100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (3, 'I', 3200);

INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (4, 'A', 9000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (4, 'B', 9100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (4, 'C', 9200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (4, 'D', 9500);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (4, 'E', 9900);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (4, 'F', 9300);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (4, 'G', 9000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (4, 'H', 9700);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (4, 'I', 9500);

INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (5, 'A', 2000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (5, 'B', 2100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (5, 'C', 2200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (5, 'D', 2500);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (5, 'E', 2300);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (5, 'F', 2100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (5, 'G', 2200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (5, 'H', 2100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (5, 'I', 2400);

INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (6, 'A', 1700);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (6, 'B', 2000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (6, 'C', 1900);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (6, 'D', 1500);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (6, 'E', 1800);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (6, 'F', 1600);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (6, 'G', 1700);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (6, 'H', 1600);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (6, 'I', 1700);

INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (7, 'A', 1800);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (7, 'B', 2000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (7, 'C', 2200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (7, 'D', 2400);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (7, 'E', 2100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (7, 'F', 2300);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (7, 'G', 2100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (7, 'H', 2000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (7, 'I', 1700);

INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (8, 'A', 2300);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (8, 'B', 2200);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (8, 'C', 2100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (8, 'D', 2000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (8, 'E', 2100);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (8, 'F', 1900);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (8, 'G', 2000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (8, 'H', 2000);
INSERT INTO PUBLIC.PRODUCT (CATEGORY_ID, BRAND, PRICE) VALUES (8, 'I', 2400);